# Role: para desinstalar o nessusagent
# Data de criação: 05/09/2023
# Utiliza o template: N/A
# 
---
- name: Remoção do Nessus Agent
  hosts: lab
  become: yes

  tasks:
    - name: Parar o serviço Nessus Agent
      service:
        name: nessusagent
        state: stopped
      ignore_errors: yes  # Ignorar erros se o serviço não estiver em execução

    - name: Remover o pacote Nessus Agent usando yum
      yum:
        name: NessusAgent
        state: absent

    - name: Remover diretório do Nessus Agent
      file:
        path: /opt/nessus_agent
        state: absent
